- block:
  - name: Add the Elasticsearch signing key
    apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present

  - name: Add the Elasticsearch repository
    apt_repository:
      repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
      state: present

  - name: Install Filebeat
    apt:
      name: filebeat

  - name: Start the Filebeat service
    systemd:
      name: filebeat
      enabled: yes
      state: started

  when: ansible_facts['distribution'] == 'Ubuntu' and ansible_facts['architecture'] == 'x86_64'
  become: yes