- block:
  - name: Add node_exporter user
    user:
      name: node_exporter
      shell: /sbin/nologin

  - name: Download node_exporter
    get_url:
      url: "{{ node_exporter_link }}"
      dest: /tmp/node_exporter.tar.gz
      mode: '0440'
    register: result
    until: result is success
    retries: 5
    delay: 3

  - name: Unarchive node_exporter
    unarchive:
      src: /tmp/node_exporter.tar.gz
      dest: /usr/sbin/
      owner: root
      group: root
      mode: '0755'
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Copy the node_exporter unit file
    copy:
      src: node_exporter.service
      dest: /etc/systemd/system
      owner: root
      group: root
      mode: '0644'

  - name: Copy the node_exporter environment file
    copy:
      src: sysconfig.node_exporter
      dest: /etc/default/node_exporter
      owner: root
      group: root
      mode: '0644'

  - name: Force systemd to reread configs
    systemd:
      daemon_reload: yes

  - name: Make the node_exporter service enabled and started
    systemd:
      name: node_exporter
      enabled: yes
      state: started
      
  when: ansible_facts['os_family'] == 'Debian' and ansible_facts['architecture'] == 'x86_64'
  become: yes
